version: 2016.2.5.{build}

build_script:
  - ps: choco pack

deploy_script:
  - ps: >-
      if($env:APPVEYOR_REPO_BRANCH -eq 'master' -And $env:APPVEYOR_REPO_TAG -eq 'true') {
        $version = $env:APPVEYOR_BUILD_VERSION -replace('\.[^.\\/]+$') ;;
        choco apiKey -k $env:Apikey -source https://chocolatey.org/ ;
        choco push datagrip.$version.nupkg
      }

artifacts:
  - path: '**\*.nupkg'
    name: Package
